### ISSUE TITLE
Error to push data into cluster

### ISSUE THREAD

**Issue by yukotakagi-es** [elastic/google-sheets-add-on#2]
"There was an error sending data to the cluster. Please check your connection details and data."

I have this error when I try to push data into cluster. Not sure where to go after.

I went back and data connection is ok.

**Comment by russorat** [comment]
fixed with https://github.com/elastic/google-sheets-add-on/commit/f1818732f7e20d550ec47b4bbc5c5eab8f2fd9f6

may have to reinstall to get the newest version.
